### ISSUE TITLE
Would be great if this worked with the Sell by Weight Plugin.  The selectors do not appear on these pages

### ISSUE THREAD

**Issue by thetonto** [codersaiful/wc-quantity-plus-minus-button#10]
https://prydebutchery.com.au/beef-mince/
Works perfectly and love it.
https://prydebutchery.com.au/chuck-steak/
Not showing as I suspect there is no CSS to hook to.

Cheers
David

**Comment by codersaiful** [comment]
Hello David, It’s not clear to me. Can u explain more please. 

Looking forward to hearing your response.

**Comment by thetonto** [comment]
Hi.  Thanks for fast response.  I run a website for a butchers shop and we use a plugin called 'Sell by Weight Pro' which from what I can determine, replaces the quantity box with its own version that then controls the total product value.  The link to the chuck steak product is one that is sold by quantity.  I had a quick look at the CSS selector for the Quantity Box is 
sbw-quantity-selector-container

Whilst the CSS selector for the quantity control for a normal woo product is 
div class="quantity wqpmb_quantity

**Comment by mdibrahimk48** [comment]
What's the issue? Could you share details about the issue?

**Comment by mdibrahimk48** [comment]
Since we haven’t heard back from you, we’re assuming that the issue has been resolved. We’re marking this issue as resolved now. If you require further assistance, please feel free to open a new issue.

Good Day!
