### ISSUE TITLE
Button border style not functioning + nothing on Cart page

### ISSUE THREAD

**Issue by joepix66** [codersaiful/wc-quantity-plus-minus-button#11]
Hi
I'm using this with Divi and the plugin works apart from a few features listed below.

1. Border radius has no effect, whatever figure you input.
2. The button border thickness/width is the same as above.
3. Input Box Settings width and height make no difference, whatever figure is applied.
4. The boxes don't show up at all on the cart page.

Both Quantity Box settings at the beginning are set to on.

Regards

**Comment by mdibrahimk48** [comment]
Hello @joepix66,

**To check this issue we need more details.** 
Please create a ticket at https://codeastrology.com/my-support
Explain all the details. If possible, provide screenshots please.

Best regards,
CodeAstrology

**Comment by joepix66** [comment]
I was about to send you info when I found the plugin had been flagged up as 'WordPress Quantity Plus Minus Button for WooCommerce by CodeAstrology plugin <= 1.1.9 - Cross Site Request Forgery (CSRF) vulnerability' by Solid Security, so I deleted it.

**Comment by mdibrahimk48** [comment]
To check this issue we need more details - Screenshots/Site URL or error log etc....

**Comment by mdibrahimk48** [comment]
Hello, as you are not giving us proper details we have closed this issue. If you need more help you can reach us via support ticket.
