### ISSUE TITLE
Cart auto-update 

### ISSUE THREAD

**Issue by webyouup** [codersaiful/wc-quantity-plus-minus-button#12]
Hello,
Elementor has the option for ajax in the cart when you increase or decrease products to auto-update, but with your plugin that isn't working anymore.

**Comment by codersaiful** [comment]
Thanks for inform us, Can you share your cart link?
Or you can make a staging site for us, we will checkout it.
Please contact over support of CodeAstrology.
Thanks

**Comment by webyouup** [comment]
https://www.elementor.marketaroma.com/en/ add a product to cart and see. 
The website is still in development, so I can create a login here.

**Comment by mdibrahimk48** [comment]
We are closing this issue because you created a support ticket and we will provide the solution in the support ticket. 
Thanks!
