### ISSUE TITLE
Not working in home page

### ISSUE THREAD

**Issue by EranChen** [codersaiful/wc-quantity-plus-minus-button#13]
Hi,
I'm trying to put ```[products]``` shortcode on my home page.
I see that the original (Woocomerce) button as disappeared but the plugin button not showing.
In archive product it's working fine.
Do you have any solution? can you help?

**Comment by codersaiful** [comment]
actually I have to check it. I will let u know ASAP.

**Comment by EranChen** [comment]
Thank you

**Comment by mdibrahimk48** [comment]
The user has not responded yet. @codersaiful

**Comment by mdibrahimk48** [comment]
Hello,

I hope everything is working fine. I am closing this issue. If you need more help, you can re-open this ticket or create a new one.

If you have any questions or need further assistance, please do not hesitate to reach out to us. We are here to provide you with the best support possible.

Thank you for choosing our plugin.

Best regards,
Team CodeAstrology
