### ISSUE TITLE
Plus and minus replicate 

### ISSUE THREAD

**Issue by sherwin40** [codersaiful/wc-quantity-plus-minus-button#16]
When I plus and click add to cart all the number in the plus and minus will be desame

**Comment by sarmina5** [comment]
Could you share the page's URL? We need to test this. Please also share the Theme's name, you are using. 

Best regards,
Sarmin
CodeAstrology

**Comment by mdibrahimk48** [comment]
I hope everything is working fine. I am closing this issue. If you need more help, you can create a new one.

If you have any questions or need further assistance, please do not hesitate to reach out to us. We are here to provide you with the best support possible.

Thank you for choosing our plugin.
