### ISSUE TITLE
Quantity button is missing

### ISSUE THREAD

**Issue by hknorst** [codersaiful/wc-quantity-plus-minus-button#17]
Hello,

I have different client roles in my shop. When the maximum quantity is set to one, the quantity button disappears, breaking the alignment.

Is there a way to show the quantity button when the maximum quantity is set to one, based on the client's role?

The issue:
![WhatsApp Image 2024-10-01 at 09 43 15](https://github.com/user-attachments/assets/aaccd09a-7912-47a9-96e1-bfe7c0207b75)

The right one:
![WhatsApp Image 2024-10-01 at 09 43 30](https://github.com/user-attachments/assets/84536753-cd62-4a88-ac25-0af03316cbab)

Best Regards

**Comment by sarmina5** [comment]
Hi,

We need more information to Check your issue. 
Could you share how you set the maximum quantity with products? This plugin only provide Plus Minus Button. Not ability to set quantity. 

Best regards,
Sarmin
CodeAstrology

**Comment by mdibrahimk48** [comment]
I hope everything is working fine. I am closing this issue. If you need more help, you can create a new one.

If you have any questions or need further assistance, please do not hesitate to reach out to us. We are here to provide you with the best support possible.

Thank you for choosing our plugin.
