### ISSUE TITLE
Quantity buttons not showing on woocommerce cart with the Divi Theme as well as not showing on product page correctly

### ISSUE THREAD

**Issue by SaajidParker** [codersaiful/wc-quantity-plus-minus-button#18]
I see that the plugin is not compatible with the current wordpress, my issue lies with it not showing correctly on the product page and also not showing up at all on the cart page as well. Attached are images regarding my problem, please help me find a solution as I have used this plugin for 2 years and it hasn't given me issues up until now.

![image_2024-10-21_141258782](https://github.com/user-attachments/assets/8f238f67-ec6b-43d0-a74b-bbb8fb8aba50)

**Comment by mdibrahimk48** [comment]
Hi Saajid,

Could you share the product page so we can test this from our end? 

Best regards,
Ibrahim

**Comment by SaajidParker** [comment]
https://uponics.co.za/product/chihiros-a-series/

It's not showing up on my cart as well, also I see the buttons aren't working correctly on mobile as well it doesn't allow me to increase or decrease the quantity

**Comment by mdibrahimk48** [comment]
Hi Saajid,

Please create a ticket at: https://codeastrology.com/my-support/ 

Please create a staging site and share the site's access. Need to debug your site.

Best regards,
Ibrahim
