### ISSUE TITLE
Automatically update cart system does not work.

### ISSUE THREAD

**Issue by mdmoinulhossain** [codersaiful/wc-quantity-plus-minus-button#19]
in elementor cart widgets, automatically update cart system is available, but your plugin does not work here. 
![Capture](https://github.com/user-attachments/assets/3ec339d1-e5f6-4673-85ba-101504f5fea6)

**Comment by minty-owen** [comment]
Yes I have the same problem.

**Comment by mdibrahimk48** [comment]
It will work as the default WooCommerce cart works. Automatic update is a premium feature of our plugin.
