### ISSUE TITLE
Button not align properly. 

### ISSUE THREAD

**Issue by wanbul** [codersaiful/wc-quantity-plus-minus-button#7]
Button is not aligned properly in Cart 
![IMG_7630](https://github.com/codersaiful/wc-quantity-plus-minus-button/assets/141735354/2a5cf0ad-1b91-4dcd-9f63-23e8ec4ecc82)

**Comment by fazlebarisn** [comment]
You may need some custom CSS. Please share your page link.

**Comment by fazlebarisn** [comment]
Has your problem been solved? Please let me know

**Comment by codersaiful** [comment]
@wanbul Can you provide your site link? Need some css code to fix it actually.
We will close this issue.
thanks
