### ISSUE TITLE
Buttons not working in the Cart page

### ISSUE THREAD

**Issue by mNemir** [codersaiful/wc-quantity-plus-minus-button#8]
Clicking the buttons in the Cart page does nothing.
Also the buttons lose their style, I think - They turn to round buttons and are not aligned correctly.

They still work well in the product pages.

![image](https://github.com/codersaiful/wc-quantity-plus-minus-button/assets/33889697/b40bf41f-8b3c-4af0-98d6-85e1d0a9be93)

**Comment by fazlebarisn** [comment]
Please share your page link. You may need some custom CSS.
Thanks

**Comment by mdibrahimk48** [comment]
Hello,

I hope everything is working fine. I am closing this issue. If you need more help, you can create a new one.

If you have any questions or need further assistance, please do not hesitate to reach out to us. We are here to provide you with the best support possible.

Thank you for choosing our plugin.

**Comment by JordanFAVRE** [comment]
Facing the same issue.
This is not due to CSS.

No errors in console. No actions taking place on click.
[Site ](https://allray.preprod.web-by-concept.com/panier/)

**Comment by mdibrahimk48** [comment]
We apologize for the inconvenience you're experiencing with our plugin.

We need more information about your site to check this issue.

**Please create a ticket at:** https://codeastrology.com/my-support/
